### ISSUE TITLE
please update your package in pypi

### ISSUE THREAD

**Issue by mehdipourfar** [sauditore/Python-Mellat#4]
last update is python-3 incompatible

**Comment by sauditore** [comment]
Can you tell me more about the error you got?

**Comment by mehdipourfar** [comment]
I'm using this fork right now.
https://github.com/sassanh/Python-Mellat

I've seen that you have merged the pull request and I just wanted to get rid of git dependency in pip requirements and use your pypi package, but it's outdated. It's last update is in 2016-06-04:
https://pypi.python.org/pypi/PyMellat/1

**Comment by sauditore** [comment]
Thanx For your comment. I will fix that soon.

**Comment by mehdipourfar** [comment]
Any news?

**Comment by sauditore** [comment]
Sorry for late, will be update on 24/03/17 bro
